POST https://localhost:3001/api/categories/category/create

{
    "name": "kids"
}

###

POST http://localhost:3001/api/categories/category/create HTTP/1.1
content-type: application/json

{
    "name": "woman"
}

###

GET http://localhost:3001/api/categories/all

###

GET http://localhost:3001/api/products/allProducts

###

POST http://localhost:3001/api/users/login
content-type: application/json

{
    "email": "admin@admin.com",
    "password": "123"
}

###
GET http://localhost:3001/api/users/user/3